INSERT INTO T2004_NhomViet_DanhMuc(TenDanhMuc)
	VALUES('Length'),
		  ('Area'),
		  ('Volume'),
		  ('Mass'),
		  ('Temperature'),
		  ('Currency'),
INSERT INTO T2004E_NhomViet_DonVi(TenDonVi,KiHieu,DanhMucID,DoPhoBien)
	VALUES('Inches','in',1,1),
	      ('Feet','ft',1,1),
		  ('Yards','yd',1,1),
		  ('millimeters','mm',1,1),
		  ('Meters','m',1,1),
		  ('kilometers','km',1,1),
		  ('centimeters','cm',1,1),

		  ('Square inches','in²',2,1),
		  ('Square feet','ft²',2,1),
		  ('Square yards','yd²',2,1),
		  ('Acres','ac',2,1),
		  ('Hecrares','Ha',2,1),
		  ('Square kilometers','km²',2,1),

		  ('fluid ounces','fl',3,1),
		  ('gallons','gal',3,1),
		  ('cubic feet','ft³',3,1),
		  ('cubic yards','yd³',3,1),

		  ('Ounces','oz',4,1),
		  ('Pounds','lb',4,1),
		  ('short tons','stn',4,1),
		  ('grams','g',4,1),
		  ('kilograms','kg',4,1),
		  ('mega grams','µg',4,1),

		  ('Fahrenheit','°F',5,1),
		  ('Celsius','°C',5,1),

		  ('VietNamese Dong','VND',6,Null),
		  ('United States Dollar','USD',6,Null),
		  ('Euro','EUR',6,Null),
		  ('Bristish Pound','GBP',6,Null),
		  ('Indian Rupee','INR',6,Null),
		  ('Australian Dollar','AUD',6,Null),
		  ('Canadian Dollar','CAD',6,Null),
		  ('Emirati Dirham','AED',6,Null),
		  ('Afghan Afhjani','AFN',6,Null),
		  ('Albanian Lek','ALL',6,Null),
		  ('Armenian Dram','AMD',6,Null),
		  ('Dutch Guilder','ANG',6,Null),
		  ('Angolan Kwanza','AOA',6,Null),
		  ('Argentine Peso','ARS',6,Null),
		  ('Aruban or Dutch Guilder','AWG',6,Null),
		  ('Azerbaijan Manat','AZN',6,Null),
		  ('Bosnian Convertible Mark','BAM',6,Null),
		  ('Barbadian or Bajan Dollar','BBD',6,Null),
		  ('Bangladeshi Taka','BDT',6,Null),
		  ('Bulgarian Lev','BGN',6,Null),
		  ('Bahraini Dinar','BHD',6,Null),
		  ('Burundian Franc','BIF',6,Null),
		  ('Bermnudian Dollar','BMD',6,Null),
		  ('Bruneian Dollar','BND',6,Null),
		  ('Bolivian Boliviano','BOB',6,Null),
		  ('Brazilian Real','BRL',6,Null),
		  ('Bahamian Dollar','BSD',6,Null),
		  ('Bhutanese Ngultrum','BTN',6,Null),
		  ('Botswana Pula','BWP',6,Null),
		  ('Belarusian Ruble','BYN',6,Null),
		  ('Belizean Dollar','BZD',6,Null),
		  ('Congolese Franc','CDF',6,Null),
		  ('Swiss Franc','CHF',6,Null),
		  ('Chilean Peso','CLP',6,Null),
		  ('Chinese Yuan Renminbi','CNY',6,Null),
		  ('Colombian Peso','COP',6,Null),
		  ('Costa Rican Colon','CRC',6,Null),
		  ('Cuban Convertible Peso','CUC',6,Null),
		  ('Cuban Peso','CUP',6,Null),
		  ('Cape Verdean Escudo','CVE',6,Null),
		  ('Czech Koruna','CZK',6,Null),
		  ('Djiboutian Franc','DJF',6,Null),
		  ('Danish Krone','DKK',6,Null),
		  ('Dominican Peso','DOP',6,Null),
		  ('Algerian Dinar','DZD',6,Null),
		  ('Egyptian Pound','EGP',6,Null),
		  ('Eritrean Nakfa','ERN',6,Null),
		  ('Ethiopiam Birr','ETB',6,Null),
		  ('Fijian Dollar','FJD',6,Null),
		  ('Falkland Island Pound','FKP',6,Null),
		  ('Georgian Lari','GEL',6,Null),
		  ('Guernsey Pound','GGP',6,Null),
		  ('Ghanaian Cedi','GHS',6,Null),
		  ('Gibraltar Pound','GIP',6,Null),
		  ('Gambian Dalasi','GMD',6,Null),
		  ('Guinean Franc','GNF',6,Null),
		  ('Guatemalan Quetzal','GTQ',6,Null),
		  ('Guyanese Dollar','GYD',6,Null),
		  ('Hong Kong Dollar','HKD',6,Null),
		  ('Honduran Lempira','HNL',6,Null),
		  ('Croatian Kuna','HRK',6,Null),
		  ('Haitian Gourde','HTG',6,Null),
		  ('Hungarian Forint','HUF',6,Null),
		  ('Indonesian Rupiah','IDR',6,Null),
		  ('Israeli Shekel','ILS',6,Null),
		  ('Isle of Man Pound','IMP',6,Null),
		  ('Iraqi Dinar','IQD',6,Null),
		  ('Iranian Rial','IRR',6,Null),
		  ('Icelandic Krona','ISK',6,Null),
		  ('Jersey Pound','JEP',6,Null),
		  ('Jamaican Dollar','JMD',6,Null),
		  ('Jordanian Dinar','JOD',6,Null),
		  ('Japanese Yen','JPY',6,Null),
		  ('Kenyan Shilling','KES',6,Null),
		  ('Kyrgyzstani Som','KGS',6,Null),
		  ('Cambodian Riel','KHR',6,Null),
		  ('Comorian Franc','KMF',6,Null),
		  ('North Korean Won','KPW',6,Null),
		  ('South Korean Won','KRW',6,Null),
		  ('Kuwaiti Dinar','KWD',6,Null),
		  ('Caymanian Dollar','KYD',6,Null),
		  ('Kazakhstani Tenge','KZT',6,Null),
		  ('Lap Kip','LAK',6,Null),
		  ('Lebanese Pound','LBP',6,Null),
		  ('Sri Lankan Rupee','LKR',6,Null),
		  ('Liberian Dollar','LRD',6,Null),
		  ('Basotho Loti','LSL',6,Null),
		  ('Libyan Dinar','LYD',6,Null),
		  ('Moroccan Dirham','MAD',6,Null),
		  ('Moldovan Leu','MDL',6,Null),
		  ('Malagasy Ariary','MGA',6,Null),
		  ('Macedonian Denar','MKD',6,Null),
		  ('Burmese Kyat','MMK',6,Null),
		  ('Mongolian Tughrik','MNT',6,Null),
		  ('Macau Pataca','MOP',6,Null),
		  ('Mauritanian Ouguiya','MRU',6,Null),
		  ('Mauritian Rupee','MUR',6,Null),
		  ('Maldivian Rufiyaa','MVR',6,Null),
		  ('Malawian Kwacha','MWK',6,Null),
		  ('Mexican Peso','MXN',6,Null),
		  ('Malaysian Ringgit','MYR',6,Null),
		  ('Mozambican Metical','MZN',6,Null),
		  ('Namibian Dollar','NAD',6,Null),
		  ('Nigerian Naira','NGN',6,Null),
		  ('Nicaraguan Cordoba','NIO',6,Null),
		  ('Norwegian Krone','NOK',6,Null),
		  ('Nepalese Rupee','NPR',6,Null),
		  ('New Zealand Dollar','NZD',6,Null),
		  ('Omani Rial','OMR',6,Null),
		  ('Panamanian Balboa','PAB',6,Null),
		  ('Peruvian Sol','PEN',6,Null),
		  ('Papua New Guinean Kina','PGK',6,Null),
		  ('Philippine Peso','PHP',6,Null),
		  ('Pakistani Rupee','PKR',6,Null),
		  ('Polish Zloty','PLN',6,Null),
		  ('Paraguayan Guarani','PYG',6,Null),
		  ('Qatari Riyal','QAR',6,Null),
		  ('Romanian Leu','RON',6,Null),
		  ('Serbian Dinar','RSD',6,Null),
		  ('Russian Ruble','RUB',6,Null),
		  ('Rwandan Franc','RWF',6,Null),
		  ('Saudi Arabian Riyal','SAR',6,Null),
		  ('Solomon Islander Dollar','SBD',6,Null),
		  ('Seychellois Rupee','SCR',6,Null),
		  ('Sudanese Pound','SDG',6,Null),
		  ('Swedish Krona','SEK',6,Null),
		  ('Singapore Dollar','SGD',6,Null),
		  ('Saint Helenian Pound','SHP',6,Null),
		  ('Sierra Leonean Leone','SLL',6,Null),
		  ('Somali Shilling','SOS',6,Null),
		  ('Seborgan Luigino','SPL',6,Null),
		  ('Surinamese Dollar','SRD',6,Null),
		  ('Sao Tomean Dobra','STN',6,Null),
		  ('Salvadoran Colon','SVC',6,Null),
		  ('Syrian Pound','SYP',6,Null),
		  ('Swazo Lolangeni','SZL',6,Null),
		  ('Thai Baht','THB',6,Null),
		  ('Tajikistani Somoni','TJS',6,Null),
		  ('Turkmenistani Manat','TMT',6,Null),
		  ('Tunisian Dinar','TND',6,Null),
		  ('Tongan Pa anga','TOP',6,Null),
		  ('Turkish Lira','TRY',6,Null),
		  ('Trinidadian Dollar','TTD',6,Null),
		  ('Tuvaluan Dollar','TVD',6,Null),
		  ('Twan New Dollar','TWD',6,Null),
		  ('Tanzanian Shilling','TZS',6,Null),
		  ('Ukrainian Hryvnia','UAH',6,Null),
		  ('Ugandan Shilling','UGX',6,Null),
		  ('Uruguayan Peso','UYU',6,Null),
		  ('Uzbekistani Som','UZS',6,Null),
		  ('Venezuelan Bolivar','VEF',6,Null),
		  ('Venezuelan Bolivar','VES',6,Null),
		  ('Ni-Vanuatu Vatu','VUV',6,Null),
		  ('Samoan Tala','WST',6,Null),
		  ('Central African CFA Franc BEAC','XAF',6,Null),
		  ('Silver Ounce','XAG',6,Null),
		  ('Gold Ounce','XAU',6,Null),
		  ('Bitcoin','XBT',6,Null),
		  ('East Caribbean Dollar','XCD',6,Null),
		  ('IMF Special Drawing Rights','XDR',6,Null),
		  ('CFA Franc','XOF',6,Null),
		  ('Oalladium Ounce','XPD',6,Null),
		  ('CFP Franc','XPF',6,Null),
		  ('Platinum Ounce','XPT',6,Null),
		  ('Yemeni Rial','YER',6,Null),
		  ('South African Rand','ZAR',6,Null),
		  ('Zambian Kwacha','ZMW',6,Null),
		  ('Zimbabwean Dollar','ZWD',6,Null)

INSERT INTO T2004E_NhomViet_SoSanh(TenSoSanh,DanhMucID,DonViQuyDoi,DonViChuan,TiLe)
	VALUES('met to met',1,'5',5,1)
	
	('inch to met',1,'1','5',0.0254),
		  ('feet to met',1,'2','5',0.3048),
		  ('yard to met',1,'3','5',0.9144),
		  ('millimet to met',1,'4','5',0.001),
		  ('kilomet to met',1,'6','5',1000),
		  ('centimet to met',1,'7','5',0.01),

		  ('VND to Dollar',6,'26','27',0.0000428962),
		  ('IDR to USD',6,'89','27',0.0000677920),
		  ('BRL to USD',6,'51','27',0.188957),
		  ('CLP to USD',6,'59','27',0.00129020),
		  ('MYR to USD',6,'126','27',0.241039),
		  ('MXN to USD',6,'125','27',0.0463315),
		  ('RON to USD',6,'143','27',0.244302)

INSERT INTO QuocGia(TenQuocGia)
	VALUES('Viet Nam'),
		  ('Indonesia'),
		  ('American'),
		  ('Brazil'),
		  ('Chile'),
		  ('Canadian'),
		  ('Malaysia'),
		  ('Mexico'),
		  ('Romania')
INSERT INTO QuocKi(Thumbnail,MaQuocGia)
	VALUES('../images/flags/vietnam-flag-xs.png',1),
		  ('../images/flags/indonesia-300x203.gif',2),
		  ('../images/flags/quốc-kỳ-hoa-kỳ-300x214.png',3),
		  ('../images/flags/quốc-kỳ-brazil-300x210.jpg',4),
		  ('../images/flags/quốc-kỳ-ChileRoI4e-300x201.gif',5),
		  ('../images/flags/quoc-ky-canada-300x200.gif',6),
		  ('../images/flags/malaysia-300x150.gif',7),
		  ('../images/flagsquốc-kỳ-mexico-300x172.jpg',8),
		  ('../images/flags/2000px-Flag_of_Romania.svg_-300x200.png',9)




SELECT * FROM T2004E_NhomViet_DonVi
SELECT ID FROM DonVi WHERE KiHieu LIKE 'IDR'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'BRL'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'CLP'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'CAD'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'MYR'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'MXN'
SELECT ID FROM DonVi WHERE KiHieu LIKE 'RON'
SELECT * FROM SoSanh
