INSERT INTO T2004E_NhomViet_DanhMuc(TenDanhMuc)
	VALUES('Length'),
		  ('Area'),
		  ('Volume'),
		  ('Mass'),
		  ('Temperature'),
		  ('Currency')

INSERT INTO T2004E_NhomViet_DonVi(TenDonVi,KiHieu,DoPhoBien,DanhMucID)
	VALUES('Inches','in',2,1),
	      ('Feet','ft',3,1),
		  ('Yards','yd',3,1),
		  ('Miles','M',3,1),
		  ('millimeters',1,'mm',1),
		  ('Meters','m',1,1),
		  ('kilometers','km',1,1),
		  ('centimeters','cm',1,1),

		  ('Square inches','in²',3,2),
		  ('Square feet','ft²',3,2),
		  ('Square yards','yd²',3,2),
		  ('Acres','ac',0,2),
		  ('Hecrares','Ha',2,2),
		  ('Square miles','M²',0,2),
		  ('Square kilometers',1,'km²',2),

		  ('fluid ounces','fl','0',3),
		  ('gallons','gal','0',3),
		  ('cubic feet','ft³',1,3),
		  ('cubic yards','yd³',1,3),

		  ('Ounces','oz',0,4),
		  ('Pounds','lb',2,4),
		  ('short tons','stn',2,4),
		  ('grams','g',1,4),
		  ('kilograms','kg',1,4),
		  ('mega grams','µg',3,4),

		  ('Fahrenheit','°F',1,5),
		  ('Celsius','°C',1,5),

		  ('VietNamese Dong','VND',6,Null),
		  ('United States Dollar','USD',6,Null),
		  ('Euro','EUR',6,Null),
		  ('Bristish Pound','GBP',6,Null),
		  ('Indian Rupee','INR',6,Null),
		  ('Australian Dollar','AUD',6,Null),
		  ('Canadian Dollar','CAD',6,Null),
		  ('Emirati Dirham','AED',6,Null),
		  ('Afghan Afhjani','AFN',6,Null),
		  ('Albanian Lek','ALL',6,Null),
		  ('Armenian Dram','AMD',6,Null),
		  ('Dutch Guilder','ANG',6,Null),
		  ('Angolan Kwanza','AOA',6,Null),
		  ('Argentine Peso','ARS',6,Null),
		  ('Aruban or Dutch Guilder','AWG',6,Null),
		  ('Azerbaijan Manat','AZN',6,Null),
		  ('Bosnian Convertible Mark','BAM',6,Null),
		  ('Barbadian or Bajan Dollar','BBD',6,Null),
		  ('Bangladeshi Taka','BDT',6,Null),
		  ('Bulgarian Lev','BGN',6,Null),
		  ('Bahraini Dinar','BHD',6,Null),
		  ('Burundian Franc','BIF',6,Null),
		  ('Bermnudian Dollar','BMD',6,Null),
		  ('Bruneian Dollar','BND',6,Null),
		  ('Bolivian Boliviano','BOB',6,Null),
		  ('Brazilian Real','BRL',6,Null),
		  ('Bahamian Dollar','BSD',6,Null),
		  ('Bhutanese Ngultrum','BTN',6,Null),
		  ('Botswana Pula','BWP',6,Null),
		  ('Belarusian Ruble','BYN',6,Null),
		  ('Belizean Dollar','BZD',6,Null),
		  ('Congolese Franc','CDF',6,Null),
		  ('Swiss Franc','CHF',6,Null),
		  ('Chilean Peso','CLP',6,Null),
		  ('Chinese Yuan Renminbi','CNY',6,Null),
		  ('Colombian Peso','COP',6,Null),
		  ('Costa Rican Colon','CRC',6,Null),
		  ('Cuban Convertible Peso','CUC',6,Null),
		  ('Cuban Peso','CUP',6,Null),
		  ('Cape Verdean Escudo','CVE',6,Null),
		  ('Czech Koruna','CZK',6,Null),
		  ('Djiboutian Franc','DJF',6,Null),
		  ('Danish Krone','DKK',6,Null),
		  ('Dominican Peso','DOP',6,Null),
		  ('Algerian Dinar','DZD',6,Null),
		  ('Egyptian Pound','EGP',6,Null),
		  ('Eritrean Nakfa','ERN',6,Null),
		  ('Ethiopiam Birr','ETB',6,Null),
		  ('Fijian Dollar','FJD',6,Null),
		  ('Falkland Island Pound','FKP',6,Null),
		  ('Georgian Lari','GEL',6,Null),
		  ('Guernsey Pound','GGP',6,Null),
		  ('Ghanaian Cedi','GHS',6,Null),
		  ('Gibraltar Pound','GIP',6,Null),
		  ('Gambian Dalasi','GMD',6,Null),
		  ('Guinean Franc','GNF',6,Null),
		  ('Guatemalan Quetzal','GTQ',6,Null),
		  ('Guyanese Dollar','GYD',6,Null),
		  ('Hong Kong Dollar','HKD',6,Null),
		  ('Honduran Lempira','HNL',6,Null),
		  ('Croatian Kuna','HRK',6,Null),
		  ('Haitian Gourde','HTG',6,Null),
		  ('Hungarian Forint','HUF',6,Null),
		  ('Indonesian Rupiah','IDR',6,Null),
		  ('Israeli Shekel','ILS',6,Null),
		  ('Isle of Man Pound','IMP',6,Null),
		  ('Iraqi Dinar','IQD',6,Null),
		  ('Iranian Rial','IRR',6,Null),
		  ('Icelandic Krona','ISK',6,Null),
		  ('Jersey Pound','JEP',6,Null),
		  ('Jamaican Dollar','JMD',6,Null),
		  ('Jordanian Dinar','JOD',6,Null),
		  ('Japanese Yen','JPY',6,Null),
		  ('Kenyan Shilling','KES',6,Null),
		  ('Kyrgyzstani Som','KGS',6,Null),
		  ('Cambodian Riel','KHR',6,Null),
		  ('Comorian Franc','KMF',6,Null),
		  ('North Korean Won','KPW',6,Null),
		  ('South Korean Won','KRW',6,Null),
		  ('Kuwaiti Dinar','KWD',6,Null),
		  ('Caymanian Dollar','KYD',6,Null),
		  ('Kazakhstani Tenge','KZT',6,Null),
		  ('Lap Kip','LAK',6,Null),
		  ('Lebanese Pound','LBP',6,Null),
		  ('Sri Lankan Rupee','LKR',6,Null),
		  ('Liberian Dollar','LRD',6,Null),
		  ('Basotho Loti','LSL',6,Null),
		  ('Libyan Dinar','LYD',6,Null),
		  ('Moroccan Dirham','MAD',6,Null),
		  ('Moldovan Leu','MDL',6,Null),
		  ('Malagasy Ariary','MGA',6,Null),
		  ('Macedonian Denar','MKD',6,Null),
		  ('Burmese Kyat','MMK',6,Null),
		  ('Mongolian Tughrik','MNT',6,Null),
		  ('Macau Pataca','MOP',6,Null),
		  ('Mauritanian Ouguiya','MRU',6,Null),
		  ('Mauritian Rupee','MUR',6,Null),
		  ('Maldivian Rufiyaa','MVR',6,Null),
		  ('Malawian Kwacha','MWK',6,Null),
		  ('Mexican Peso','MXN',6,Null),
		  ('Malaysian Ringgit','MYR',6,Null),
		  ('Mozambican Metical','MZN',6,Null),
		  ('Namibian Dollar','NAD',6,Null),
		  ('Nigerian Naira','NGN',6,Null),
		  ('Nicaraguan Cordoba','NIO',6,Null),
		  ('Norwegian Krone','NOK',6,Null),
		  ('Nepalese Rupee','NPR',6,Null),
		  ('New Zealand Dollar','NZD',6,Null),
		  ('Omani Rial','OMR',6,Null),
		  ('Panamanian Balboa','PAB',6,Null),
		  ('Peruvian Sol','PEN',6,Null),
		  ('Papua New Guinean Kina','PGK',6,Null),
		  ('Philippine Peso','PHP',6,Null),
		  ('Pakistani Rupee','PKR',6,Null),
		  ('Polish Zloty','PLN',6,Null),
		  ('Paraguayan Guarani','PYG',6,Null),
		  ('Qatari Riyal','QAR',6,Null),
		  ('Romanian Leu','RON',6,Null),
		  ('Serbian Dinar','RSD',6,Null),
		  ('Russian Ruble','RUB',6,Null),
		  ('Rwandan Franc','RWF',6,Null),
		  ('Saudi Arabian Riyal','SAR',6,Null),
		  ('Solomon Islander Dollar','SBD',6,Null),
		  ('Seychellois Rupee','SCR',6,Null),
		  ('Sudanese Pound','SDG',6,Null),
		  ('Swedish Krona','SEK',6,Null),
		  ('Singapore Dollar','SGD',6,Null),
		  ('Saint Helenian Pound','SHP',6,Null),
		  ('Sierra Leonean Leone','SLL',6,Null),
		  ('Somali Shilling','SOS',6,Null),
		  ('Seborgan Luigino','SPL',6,Null),
		  ('Surinamese Dollar','SRD',6,Null),
		  ('Sao Tomean Dobra','STN',6,Null),
		  ('Salvadoran Colon','SVC',6,Null),
		  ('Syrian Pound','SYP',6,Null),
		  ('Swazo Lolangeni','SZL',6,Null),
		  ('Thai Baht','THB',6,Null),
		  ('Tajikistani Somoni','TJS',6,Null),
		  ('Turkmenistani Manat','TMT',6,Null),
		  ('Tunisian Dinar','TND',6,Null),
		  ('Tongan Pa anga','TOP',6,Null),
		  ('Turkish Lira','TRY',6,Null),
		  ('Trinidadian Dollar','TTD',6,Null),
		  ('Tuvaluan Dollar','TVD',6,Null),
		  ('Twan New Dollar','TWD',6,Null),
		  ('Tanzanian Shilling','TZS',6,Null),
		  ('Ukrainian Hryvnia','UAH',6,Null),
		  ('Ugandan Shilling','UGX',6,Null),
		  ('Uruguayan Peso','UYU',6,Null),
		  ('Uzbekistani Som','UZS',6,Null),
		  ('Venezuelan Bolivar','VEF',6,Null),
		  ('Venezuelan Bolivar','VES',6,Null),
		  ('Ni-Vanuatu Vatu','VUV',6,Null),
		  ('Samoan Tala','WST',6,Null),
		  ('Central African CFA Franc BEAC','XAF',6,Null),
		  ('Silver Ounce','XAG',6,Null),
		  ('Gold Ounce','XAU',6,Null),
		  ('Bitcoin','XBT',6,Null),
		  ('East Caribbean Dollar','XCD',6,Null),
		  ('IMF Special Drawing Rights','XDR',6,Null),
		  ('CFA Franc','XOF',6,Null),
		  ('Oalladium Ounce','XPD',6,Null),
		  ('CFP Franc','XPF',6,Null),
		  ('Platinum Ounce','XPT',6,Null),
		  ('Yemeni Rial','YER',6,Null),
		  ('South African Rand','ZAR',6,Null),
		  ('Zambian Kwacha','ZMW',6,Null),
		  ('Zimbabwean Dollar','ZWD',6,Null)


INSERT INTO T2004E_NhomViet_QuocGia(TenQuocGia,QuocKi)
	VALUES('Romania','../images/flags/2000px-Flag_of_Romania.svg_-300x200.png'),
		  ('Switzerland','../images/flags/3857101_640px-300x200.jpg'),
		  ('Russian','../images/flags/2096155911-300x201.jpg'),
		  ('Saudi Arabia','../imgaes/flags/a-rap-xe-ut-300x200.gif'),
		  ('Afghanistan','../images/flags/afghanistan-300x150.gif'),
		  ('Indian','../images/flags/an-do-300x201.gif'),
		  ('Angola','../images/flags/angola-flat-300x201.gif'),
		  ('Antillen belanda','../images/flags/Antillen-thuoc-ha-lan-300x199.gif'),
		  ('Armenian','../images/flags/armenia-300x150.png'),
		  ('Azerbaijan','../images/flags/azerbaijan-300x150.png'),
		  ('Bahrain','../images/flags/bahrain-300x179.gif'),
		  ('Bangladesh','../images/flags/bangladesh-300x180.gif'),
		  ('Benin','../images/flags/benin-flag-300x200.gif'),
		  ('Bhutan','../images/flags/bhutan-300x200.gif'),
		  ('Bosnia and Herzegovina','../images/flags/bosnia-herzegovina-300x150.gif'),
		  ('Botswana','../images/flags/botswana-flat-300x200.gif'),
		  ('Brunei','../images/flags/brunei-300x152.gif'),
		  ('Burkina Faso','../images/flags/Burkina_Faso-flat-300x200.png'),
		  ('Burundi','../images/flags/burundi-flag-300x199.gif'),
		  ('Cameroon','../images/flags/cameroon-flag-300x200.gif'),
		  ('Campuchia','../images/flags/campuchia-300x203.gif'),
		  ('Cape Verde','../images/flags/cape-verde-flag-300x175.gif'),
		  ('Central African Republic','../images/flags/Central-African-Republic-flat-300x200.gif'),
		  ('Chad','../images/flags/chad-flag-300x199.gif'),
		  ('Sweden','../images/flags/cheap-calling-to-sweden-flag-300x225.jpg'),
		  ('Algeria','../images/flags/co-algeria-300x200.png'),
		  ('Poland','../images/flags/co-ba-lan-400x250-300x188.jpg'),
		  ('Comoros','../images/flags/comoros-flag-300x200.gif'),
		  ('Dominican Republic','../images/flags/cong-hoa-dominican-300x204.gif'),
		  ('Democratic Republic of the Congo','../images/flags/congo-kinshasa-flag-300x225.png'),
		  ('Republic of the Congo','../images/flags/congo-republic-flag-300x170.jpg'),
		  ('Côte dIvoire','../images/flags/cote-divoire-300x200.gif'),
		  ('Taiwan','../images/flags/dai-loan-300x200.gif'),
		  ('Djibouti','../images/flags/djibouti-300x200.gif'),
		  ('Timor-Leste','../images/flags/dong-timor-300x150.png'),
		  ('Germany','../images/flags/Duc_Flag-300x200.png'),
		  ('Egypt','../images/flags/egypt-flat-300x200.gif'),
		  ('Equatorial Guinea','../images/flags/Equatorial_Guinea_Flag-300x199.jpg'),
		  ('Eritrea','../images/flags/Eritrea-flag-300x150.png'),
		  ('Ethiopia','../images/flags/ethiopia-flag-300x150.gif'),
		  ('Fiji','../images/flags/fiji-300x149.gif'),
		  ('Finland','../images/flags/Finland228.svg_-300x183.png'),
		  ('France','../images/flags/Flag_of_France.svg_-300x200.png'),
		  ('Gabon','../images/flags/gabon-300x203.gif'),
		  ('The Gambia','../images/flags/gambia-300x200.gif'),
		  ('Georgia','../images/flags/georgia-300x200.gif'),
		  ('Ghana','../images/flags/ghana-300x200.png'),
		  ('Guam','../images/flags/guam-300x150.gif'),
		  ('Guinea','../images/flags/guinea-300x203.gif'),
		  ('Guinea-Bissau','../images/flags/guinea-bissau-300x150.gif'),
		  ('Korean','../images/flags/han-quoc-300x200.gif'),
		  ('Belgium','../images/flags/image001-1-300x174.jpg'),
		  ('Ukraina','../images/flags/image001-300x201.jpg'),
		  ('Indonesia','../images/flags/indonesia-300x203.gif'),
		  ('Iran','../images/flags/iran-300x169.gif'),
		  ('Iraq','../images/flags/iraq-300x200.png'),
		  ('Ireland','../images/flags/Ireland218.svg_-300x150.png'),
		  ('Israel','../images/flags/israel-300x218.gif'),
		  ('Jordan','../images/flags/jordan-300x150.png'),
		  ('Kazakhstan','../images/flags/kazakhstan-300x200.gif'),
		  ('Kenya','../images/flags/kenya-300x199.gif'),
		  ('Kiribati','../images/flags/kiribati-300x200.gif'),
		  ('Kuwait','../images/flags/kuwait-300x150.gif'),
		  ('Kyrgyzstan','../images/flags/kyrgyzstan-300x200.gif'),
		  ('Kosovo','../images/flags/la-co-kosovo-300x214.png'),
		  ('Lao','../images/flags/lao-300x200.gif'),
		  ('Lesotho','../images/flags/lesotho-300x200.gif'),
		  ('Liban','../images/flags/liban-300x200.gif'),
		  ('Liberia','../images/flags/liberia-300x155.gif'),
		  ('Libya','../images/flags/libya-300x149.gif')
		  ('Federated States of Micronesia','../images/flags/lien-bang-micronesia-300x183.gif'),
		  ('Madagascar','../images/flags/madagascar-300x200.gif'),
		  ('Malawi','../images/flags/malawi-300x203.gif'),
		  ('Malaysia','../images/flags/malaysia-300x150.gif'),
		  ('Maldives','../images/flags/maldives-300x198.gif'),
		  ('Mali','../images/flags/mali-300x198.gif'),
		  ('Mauritania','../images/flags/mauritania-300x200.gif'),
		  ('Mauritius','../images/flags/mauritius-300x201.gif'),
		  ('Mongolia','../images/flags/mong-co-300x149.gif'),
		  ('Montserrat','../images/flags/montserrat-300x149.gif'),
		  ('Morocco','../images/flags/morocco-300x198.gif'),
		  ('Mozambique','../images/flags/mozambique-300x200.png'),
		  ('Myanmar (Burma)','../images/flags/myanmar-300x200.png'),
		  ('Norway','../images/flags/na-uy-300x169.jpg'),
		  ('South Africa','../images/flags/nam-phi-300x200.png'),
		  ('South Sudan','../images/flags/nam-sudan-300x150.png'),
		  ('Namibia','../images/flags/namibia-300x200.gif'),
		  ('Greece','../images/flags/national-flag-of-greece-clip-art-9131-300x172.jpg'),
		  ('Nauru','../images/flags/nauru-300x151.gif'),
		  ('Nepal','../images/flags/nepal-229x300.gif'),
		  ('New Zealand','../images/flags/new-zealand-300x150.gif'),
		  ('Japan','../images/flags/nhat-ban-300x201.gif'),
		  ('Niger','../images/flags/niger-300x198.gif'),
		  ('Nigeria','../images/flags/Nigeria_flag-300x149.gif'),
		  ('Oman','../images/flags/oman-300x200.gif'),
		  ('Palau','../images/flags/palau-300x200.gif'),
		  ('Palestine','../images/flags/palestine-300x150.gif'),
		  ('Papua New Guinea','../images/flags/papua-new-guinea-300x220.gif'),
		  ('Philippines','../images/flags/philippines-300x149.gif'),
		  ('Pitcairn Islands','../images/flags/pitcairn-300x149.gif'),
		  ('Polynesia','../images/flags/Polyneisa-thuoc-phap-300x169.gif'),
		  ('Qatar','../images/flags/qatar-300x118.png'),
		  ('Northern Mariana Islands','../images/flags/quan-dao-bac-mariana-300x150.gif'),
		  ('Marshall Islands','../images/flags/quan-dao-marshall-300x150.gif'),
		  ('Solomon Islands','../images/flags/quan-dao-solomon-300x200.gif'),
		  ('Andorra','../images/flags/quoc-ky-andorra-300x211.gif'),
		  ('Austria','../images/flags/quoc-ky-cac-nuoc-anh_3-300x169.png'),
		  ('Canada','../images/flags/quoc-ky-canada-300x200.gif'),
		  ('Denmark','../images/flags/quoc-ky-dan-mach-300x247.gif'),
		  ('Anguilla','../images/flags/quoc-ky-dat-nuoc-Anguilla-300x150.gif'),
		  ('Belarus','../images/flags/quoc-ky-dat-nuoc-Belaruscxts5-300x150.gif'),
		  ('Bermuda','../images/flags/quoc-ky-dat-nuoc-Bermuda-300x150.gif'),
		  ('Bulgaria','../images/flags/quoc-ky-dat-nuoc-BulgariaksX8Z-300x200.gif'),
		  ('Croatia','../images/flags/quoc-ky-dat-nuoc-Croatiajb4Vw-300x152.gif'),
		  ('Hungary','../images/flags/quoc-ky-dat-nuoc-HungarydrDm8-300x200.gif'),
		  ('Estonia','../images/flags/quoc-ky-Estoniaws-300x201.gif'),
		  ('Guatemala','../images/flags/quoc-ky-Guatemala-300x200.gif'),
		  ('Haiti','../images/flags/quoc-ky-Haiti-300x200.gif'),
		  ('Latvia','../images/flags/quoc-ky-Latvia-300x200.gif'),
		  ('Nicaragua','../images/flags/quoc-ky-Nicaragua-300x180.png'),
		  ('Slovenia','../images/flags/quoc-ky-slovenia-300x150.png'),
		  ('Colombia','../images/flags/quoc-kyColombia-300x200.gif'),
		  ('','../images/flags/quốc-kỳ.png'),
		  ('Albania','../images/flags/quốc-kỳ-Albania-300x216.gif'),
		  ('Antigua and Barbuda','../images/flags/quốc-kỳ-Antigua-and-BarbudaI-300x200.gif'),
		  ('Argentina','../images/flags/quốc-kỳ-Argentina-300x193.png'),
		  ('Aruba','../images/flags/quốc-kỳ-Aruba-300x169.jpg'),
		  ('Bahamas','../images/flags/quốc-kỳ-Bahamas-300x150.gif'),
		  ('Barbados','../images/flags/quốc-kỳ-Barbados-300x200.png'),
		  ('Belize','../images/flags/quốc-kỳ-Belize-300x200.png'),
		  ('Bolivia','../images/flags/quốc-kỳ-Bolivia-300x204.png'),
		  ('Brazil','../images/flags/quốc-kỳ-brazil-300x210.jpg'),
		  ('Chile','../images/flags/quốc-kỳ-ChileRoI4e-300x201.gif'),
		  ('Costa Rica','../images/flags/quốc-kỳ-Costa_Rica-300x180.png'),
		  ('Cuba','../images/flags/quốc-kỳ-cuba-300x200.png'),
		  ('Domonica','../images/flags/quốc-kỳ-Dominica-300x150.png'),
		  ('Ecuador','../images/flags/quốc-kỳ-Ecuador-300x200.png'),
		  ('Falkland Islands','../images/flags/quốc-kỳ-Falkland_Islands.svg_-300x150.png'),
		  ('Grenada','../images/flags/quốc-kỳ-Grenada-300x150.png'),
		  ('Guadeloupe','../images/flags/quốc-kỳ-Guadeloupe.png'),
		  ('French Guiana','../images/flags/Quốc-kỳ-guiana-thuộc-pháp-300x200.png'),
		  ('Guyana','../images/flags/quốc-kỳ-Guyana-300x180.png'),
		  ('America','../images/flags/quốc-kỳ-hoa-kỳ-300x214.png'),
		  ('Iceland','../images/flags/quốc-kỳ-Iceland.png'),
		  ('Jamaica','../images/flags/Quốc-kỳ-Jamaica-300x150.gif'),
		  ('Liechtenstein','../images/flags/quốc-kỳ-liechtenstein1-300x200.gif'),
		  ('Luxembourg','../images/flags/quốc-kỳ-Luxembourg.png'),
		  ('Maarten','../images/flags/quốc-kỳ-Maarten-300x200.png'),
		  ('Macedonia','../images/flags/quốc-kỳ-Macedonia-300x200.gif'),
		  ('Malta','../images/flags/quốc-kỳ-malta-300x200.png'),
		  ('Mexico','../images/flags/quốc-kỳ-mexico-300x172.jpg'),
		  ('Moldova','../images/flags/quốc-kỳ-Moldova.svg_-300x150.png'),
		  ('Monaco','../images/flags/quốc-kỳ-monaco-300x180.jpg'),
		  ('Montenegro','../images/flags/quốc-kỳ-Montenegro.png'),
		  ('Panama','../images/flags/quốc-kỳ-panama-300x197.gif'),
		  ('Paraguay','../images/flags/quốc-kỳ-Paraguay.svg_-300x165.png'),
		  ('Puerto Rico','../images/flags/quốc-kỳ-puerto-rico-300x150.gif'),
		  ('South Georgia and the South Sandwich Islands','../images/flags/quốc-kỳ-Quần-đảo-Nam-Georgia-và-Nam-Sandwich-300x150.jpg'),
		  ('Turks and Caicos Islands','../images/flags/quốc-kỳ-Quần-đảo-Turks-và-Caicos--300x150.jpg'),
		  ('','../images/flags/quốc-kỳ-quần-đảo-Virgin-thuộc-Anh-300x150.png'),
		  ('U.S. Virgin Islands','../images/flags/quốc-kỳ-quần-đảo-Virgin-thuộc-Mỹ-300x200.jpg'),
		  ('British Virgin Islands','../images/flags/quốc-kỳ-Saint-Kitts-và-Nevis-300x200.jpg'),
		  ('Saint Lucia','../images/flags/quốc-kỳ-Saint-Lucia-300x150.png'),
		  ('Saint Pierre and Miquelon','../images/flags/quốc-kỳ-Saint-Pierre-và-Miquelon-300x188.gif'),
		  ('San Marino','../images/flags/quốc-kỳ-san-marino-300x225.png'),
		  ('Serbia','../images/flags/quốc-kỳ-serbia-300x200.jpg'),
		  ('Suriname','../images/flags/quốc-kỳ-Suriname-300x201.gif'),
		  ('Trinidad and Tobago','../images/flags/quốc-kỳ-Trinidad-và-Tobago-300x203.jpg'),
		  ('Uruguay','../images/flags/quốc-kỳ-Uruguay.png'),
		  ('Venezuela','../images/flags/quốc-kỳ-Venezuela-300x200.png'),
		  ('Saint Vincent and the Grenadines','../images/flags/quốc-kỳ-Vincent_and_the_Grenadines.-300x200.png'),
		  ('El Salvador','../images/flags/quốc-kỳ_El_Salvador-300x169.png'),
		  ('Honduras','../images/flags/quốc-kỳ_Honduras-300x150.png'),
		  ('Peru','../images/flags/quốc-kỳPeru-300x200.png'),
		  ('Reunion','../images/flags/reunion-300x201.gif'),
		  ('Rwanda','../images/flags/rwanda-300x200.jpg'),
		  ('Samoa','../images/flags/samoa-300x151.gif'),
		  ('American Samoa','../images/flags/samoa-thuoc-my-300x154.gif'),
		  ('Sao Tome and Príncipe','../images/flags/sao-tome-va-principe-300x152.gif'),
		  ('Senegal','../images/flags/senegal-300x200.gif'),
		  ('Sierra Leone','../images/flags/sierra-leone-300x200.gif'),
		  ('Singapore','../images/flags/singapore-300x200.gif'),
		  ('Cyprus','../images/flags/sip-300x180.gif'),
		  ('Slovakia','../images/flags/Slovakia_flag_300-300x200.png'),
		  ('Somalia','../images/flags/Somalia-300x197.gif'),
		  ('Sri Lanka','../images/flags/sri-lanka-300x151.gif'),
		  ('Sudan','../images/flags/sudan-300x150.png'),
		  ('Swaziland','../images/flags/swaziland-300x193.gif'),
		  ('Syria','../images/flags/syria-300x191.gif'),
		  ('Tanzania','../images/flags/tanzania-300x201.gif'),
		  ('Thailand','../images/flags/thai-lan-300x198.gif'),
		  ('Vatican City','../images/flags/thanh-vatican-300x300.gif'),
		  ('Turkey','../images/flags/Tho-300x225.jpg'),
		  ('Togo','../images/flags/togo-300x203.gif'),
		  ('Tonga','../images/flags/tonga-300x150.gif'),
		  ('North Korea','../images/flags/trieu-tien-300x152.gif'),
		  ('China','../images/flags/trung-quoc-300x198.gif'),
		  ('Tunisia','../images/flags/tunisia-300x200.gif'),
		  ('Turkmenistan','../images/flags/turkmenistan-300x200.png'),
		  ('Tuvalu','../images/flags/tuvalu-300x150.gif'),
		  ('Portugal','../images/flags/tải-xuống.jpg'),
		  ('Czechia','../images/flags/tải-xuống.png'),
		  ('UAE','../images/flags/uae-300x149.gif'),
		  ('Australia','../images/flags/uc-300x152.gif'),
		  ('Uganda','../images/flags/uganda-300x180.gif'),
		  ('British','../images/flags/UnionFlag-300x180.png'),
		  ('Uzbekistan','../images/flags/uzbekistan-300x150.png'),
		  ('Vanuatu','../images/flags/vanuatu-300x188.gif'),
		  ('Spain','../images/flags/vfinance_spain-flag-300x200.gif'),
		  ('Viet Nam','../images/flags/viet-nam-300x200.gif'),
		  ('Netherlands','../images/flags/vn_110316122614Quoc-ky-Ha-Lan-300x200.gif'),
		  ('Italy','../images/flags/y-300x200.png'),
		  ('Yemen','../images/flags/yemen-300x200.png'),
		  ('Zambia','../images/flags/zambia-300x200.png'),
		  ('Zimbabwe','../images/flags/zimbabwe-300x150.gif')




